Repository TuiChain/backend, pull requests merged in 2021-01, with the labels that each got.

#30 Added view to fetch non validated loan requests
  tuichain/api/views/loanrequests.py
  tuichain/urls.py
Labels: enhancement

#47 Hp/bc connection
  .env_sample
  .vscode/settings.json
  tuichain/api/__init__.py
  tuichain/api/migrations/0001_initial.py
  tuichain/api/migrations/0002_idverifications.py
  tuichain/api/models.py
  tuichain/api/services/blockchain.py
  tuichain/api/views/auth.py
  tuichain/api/views/blockchain.py
  tuichain/api/views/loanrequests.py
  tuichain/urls.py
Labels: enhancement

#50 return dai_contract_address
  tuichain/api/views/blockchain.py
Labels: enhancement

#54 Hp/admin route
  tuichain/api/views/auth.py
  tuichain/settings.py
  tuichain/urls.py
Labels: bug, enhancement

#59 fix route
  tuichain/api/views/loanrequests.py
Labels: bug

#72 rm/alter_models
  tuichain/api/enums.py
  tuichain/api/migrations/0001_initial.py
  tuichain/api/migrations/0002_auto_20210112_1928.py
  tuichain/api/migrations/0003_auto_20210112_1946.py
  tuichain/api/models.py
  tuichain/api/serializers.py
  tuichain/api/views/investments.py
  tuichain/api/views/loans.py
  tuichain/urls.py
Labels: enhancement

#75 Changed GET methods for loans
  requirements.txt
  tuichain/api/models.py
  tuichain/api/views/loans.py
  tuichain/urls.py
Labels: enhancement

#91 Rm/add funding fee
  tuichain/api/views/loans.py
Labels: enhancement

#92 Rm/finalize loan
  tuichain/api/views/loans.py
  tuichain/urls.py
Labels: enhancement

#93 Rm/add current price
  tuichain/api/views/loans.py
Labels: enhancement

#96 Documents
  .env_test
  requirements.txt
  tuichain/api/migrations/0001_initial.py
  tuichain/api/models.py
  tuichain/api/services/storage.py
  tuichain/api/views/loans.py
  tuichain/api/views/users.py
  tuichain/creds.json
  tuichain/settings.py
  tuichain/urls.py
Labels: enhancement

#101 Added profile pic to response
  tuichain/api/views/loans.py
Labels: enhancement

#106 Added user full name to response
  tuichain/api/views/users.py
Labels: enhancement
